define({

"LoginContainerHeaderText": "Interaction Web Tools",
"MainPanelHeaderText": "Interaction Web Tools",
"ClosePageWarning": "Are you sure you want to disconnect your current chat? Your option to receive a transcript will be lost.",
"ExitChatWarning": "Are you sure you want to disconnect your current chat? Your option to receive a transcript will be lost.",
"OutOfOrderMessage": "This message have been delivered out of order:",
"StartChatButton": "Start Chat",
"StartChatTab": "Chat",
"StartCallbackButton": "Start Callback",
"StartCallbackTab": "Callback",
"RegisterNewAccountTab": "Create an Account",
"Login": "Login",
"Register": "Register",
"IHaveAnAccount": "I have an account",
"IDontHaveAnAccount": "I don't have an account",
"CreateAnAccount": "Create an account",
"OptionalTag": "(Optional)",
"NameLabel": "Name:",
"DescriptionLabel": "Description:",
"TelephoneLabel": "Telephone:",
"PasswordLabel": "Password:",
"ConfirmPasswordLabel": "Confirm Password:",
"UserNameLabel": "Username:",
"lastNameLabel": "Last Name:",
"firstNameLabel": "First Name:",
"middleNameLabel": "Middle Name:",
"departmentLabel": "Department:",
"companyLabel": "Company:",
"jobTitleLabel": "Job Title:",
"assistantNameLabel": "Assistant Name:",
"webLoginLabel": "Web Login:",
"webPasswordLabel": "Web Password:",
"homeStreetAddressLabel": "Street Address:",
"homeCityLabel": "City:",
"homeStateLabel": "State:",
"homePostalCodeLabel": "Zip:",
"homeCountryLabel": "Country:",
"homeEmailLabel": "E-mail:",
"homePhoneLabel": "Phone:",
"homePhone2Label": "Additional Phone:",
"homeFaxLabel": "Fax:",
"homePagerLabel": "Pager:",
"homeMobileLabel": "Mobile:",
"homeUrlLabel": "URL:",
"businessStreetAddressLabel": "Street Address:",
"businessCityLabel": "City:",
"businessStateLabel": "State:",
"businessPostalCodeLabel": "Zip:",
"businessCountryLabel": "Country:",
"businessEmailLabel": "E-mail:",
"businessPhoneLabel": "Phone:",
"businessPhone2Label": "Additional Phone:",
"businessFaxLabel": "Fax:",
"businessPagerLabel": "Pager:",
"businessMobileLabel": "Mobile:",
"businessUrlLabel": "URL:",
"assistantPhoneLabel": "Assistant Phone:",
"remarksLabel": "Remarks:",
"LoginFailed": "Login failed",
"RegistrationSucceeded": "Registration succeeded",
"RegistrationFailed": "Registration failed",
"CallbackSucceeded": "An agent will call you back as soon as possible",
"CallbackFailed": "Callback failed",
"CreateCallback": "Submit",
"InProcess": "In Process",
"Waiting": "Waiting",
"CallbackCreatorNameLabel": "Requestor:",
"CallbackCreationDateTimeLabel": "Requested at:",
"AssignedAgentLabel": "Assigned Agent:",
"CallbackStateLabel": "State:",
"EstimatedCallbackTimeLabel": "Estimated callback time:",
"WaitTimeLabel": "Average wait time:",
"QueuePositionLabel": "Position in %0 queue:",
"LongestWaitTimeLabel": "Longest wait time:",
"TimeDuration_Minute": "About a minute",
"TimeDuration_Minutes": "About %0 minutes",
"TimeDuration_Minutes_AlternatePlural": "About %0 minutes",
"TimeDuration_Hour": "About an hour",
"TimeDuration_Hours": "About %0 hours",
"TimeDuration_Hours_AlternatePlural": "About %0 hours",
"TimeDuration_Day": "About a day",
"TimeDuration_Days": "About %0 days",
"TimeDuration_Days_AlternatePlural": "About %0 days",
"InteractionsWaitingCountLabel": "Interactions waiting:",
"LoggedInAgentsCountLabel": "Logged in agents:",
"AvailableAgentsCountLabel": "Available agents:",
"Callback": "Callback",
"CallbackStatusFailed": "Couldn't get the status of the callback.",
"UserIdLabel": "User ID:",
"DisconnectCallback": "Cancel",
"DisconnectCallbackSucceeded": "The callback request has been canceled.",
"DisconnectCallbackFailed": "Failed to cancel this callback request",
"EnterNameIfDesired": "Enter name if desired",
"AnonymousUser": "Anonymous User",
"Account": "Account",
"Name": "Name",
"Home": "Home",
"Business": "Business",
"OneErrorWithChatData": "There was one error with the chat information.",
"MultipleErrorsWithChatData": "There were %0 errors with the chat information.",
"OneErrorWithRegistrationData": "There was one error with the registration information.",
"MultipleErrorsWithRegistrationData": "There were %0 errors with the registration information.",
"OneErrorWithCallbackData": "There was one error with the callback information.",
"MultipleErrorsWithCallbackData": "There were %0 errors with the callback information.",
"FieldIsRequired": "Field is required",
"PasswordsDoNotMatch": "Passwords do not match",
"GeneralError": "General error",
"InvalidCharSetError": "Character set of content is invalid",
"InvalidContentTypeError": "Type of content is invalid",
"ContentError": "Content is invalid",
"MissingDataError": "Content is missing required data",
"UnknownEntityError": "Unknown entity",
"UnknownSessionError": "Unknown session",
"UnknownParticipantError": "Unknown participant",
"BadTargetError": "Unknown ACD target",
"UserDbError": "User account error",
"UserNotOnline": "User is not online",
"BadCredentialsError": "User name or password is incorrect",
"AccountExistsError": "Account already exists",
"FailedToSendMessage": "Failed to send message",
"ErrorConnectingToServer": "There was an error connecting to the server",
"SendOnEnter": "Press Enter to send message",
"Send": "Send",
"Exit": "Exit",
"DisconnectedFromChat": "You have been disconnected from the chat",
"ErrorConnectingServer": "Error connecting to the server. Please wait while we try to reconnect...",
"SuccessfullyReconnectedServer": "Successfully reconnected to the server.",
"CouldNotConnectServerRetry": "Could not connect to any servers. Will retry in a moment.",
"PleaseLeaveMessage": "Please leave a message for %0",
"PrintableChatHistory": "Printable chat history",
"ChatHistory": "Chat History",
"Print": "Print",
"LinkDisclaimer": "*Some links may not be valid after the chat ends.",
/* Note that the following line uses single quotes, to avoid having nested double quotes. */
"NeedPageRefresh_Format": 'Sorry for the inconvenience, but we have encountered a system failure that will require you to <a href="{0}">start a new chat</a>.',
"BrowserSecuritySettingsError": "Web browser security settings will not allow Interaction Web Tools to run.",
"FireFoxVersionError": "FireFox versions prior to 3.5 are not supported",
"IEVersionError": "Internet Explorer versions prior to 7 are not supported",
"ErrorOpeningWindow": "There was an error opening the window.",

"Typing": "(typing)",
"LastRespondedTime": "Last response sent at: %0",
"Disclaimer": "Disclaimer: Subject of callbacks and content of chats might be monitored, recorded, or viewed by agents and supervisors for quality monitoring and routing and distribution purposes.",

"DayOfWeek0": "Sunday",
"DayOfWeek1": "Monday",
"DayOfWeek2": "Tuesday",
"DayOfWeek3": "Wednesday",
"DayOfWeek4": "Thursday",
"DayOfWeek5": "Friday",
"DayOfWeek6": "Saturday",
"AbbreviatedDayOfWeek0": "Sun",
"AbbreviatedDayOfWeek1": "Mon",
"AbbreviatedDayOfWeek2": "Tue",
"AbbreviatedDayOfWeek3": "Wed",
"AbbreviatedDayOfWeek4": "Thu",
"AbbreviatedDayOfWeek5": "Fri",
"AbbreviatedDayOfWeek6": "Sat",

"Month1": "January",
"Month2": "February",
"Month3": "March",
"Month4": "April",
"Month5": "May",
"Month6": "June",
"Month7": "July",
"Month8": "August",
"Month9": "September",
"Month10": "October",
"Month11": "November",
"Month12": "December",
"AbbreviatedMonth1": "Jan",
"AbbreviatedMonth2": "Feb",
"AbbreviatedMonth3": "Mar",
"AbbreviatedMonth4": "Apr",
"AbbreviatedMonth5": "May",
"AbbreviatedMonth6": "Jun",
"AbbreviatedMonth7": "Jul",
"AbbreviatedMonth8": "Aug",
"AbbreviatedMonth9": "Sep",
"AbbreviatedMonth10": "Oct",
"AbbreviatedMonth11": "Nov",
"AbbreviatedMonth12": "Dec",

"AM": "a.m.",
"PM": "p.m.",
"AbbreviatedAM": "a",
"AbbreviatedPM": "p",

"Era": "CE",
"AbbreviatedEra": "CE",

"FallbackDateFormat": "d MMM yyyy",
"FallbackTimeFormat": "h:mm tt",

"OverrideDateTimeFormats": "0",

"LanguageCode": "en-us",
"TextDirection": "ltr"
});
